apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: ta-ardi-autoscaling-2
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
            - image: us-central1-docker.pkg.dev/ml-autoscaling/ml-autoscaling-image-registry/horovod:v0.1.46-autoscale-cpu
              name: mpi-launcher
              command:
                - horovodrun
              args:
                - -np
                - "1"
                - --host-discovery-script
                - /etc/mpi/discover_hosts.sh
                - python
                - /autoscale/tensorflow2_mnist_elastic_test.py
                - --batch-size
                - "64"
                - --num-epochs
                - "5"
                - --batches-per-epoch
                - "1000"
                - --autoscale
                - --autoscale-min-worker
                - "1"
                - --autoscale-max-worker
                - "8"
                - --autoscale-delta-worker
                - "1"
                - --autoscale-efficiency-threshold
                - "0.7"
                - --autoscale-throughput-average-batches
                - "10"
              resources:
                limits:
                  cpu: 1
                  memory: 2Gi
          serviceAccountName: ml-autoscaling
    Worker:
      replicas: 2
      template:
        spec:
          containers:
            - image: us-central1-docker.pkg.dev/ml-autoscaling/ml-autoscaling-image-registry/horovod:v0.1.46-autoscale-cpu
              name: mpi-worker
              resources:
                limits:
                  cpu: 1
                  memory: 2Gi
          serviceAccountName: ml-autoscaling
