---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ml-autoscaling
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ml-autoscaling-mpijobs-edit
rules:
  - apiGroups:
      - kubeflow.org
    resources:
      - mpijobs
      - mpijobs/status
    verbs:
      - get
      - list
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ml-autoscaling
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ml-autoscaling-mpijobs-edit
subjects:
  - kind: ServiceAccount
    name: ml-autoscaling
---
