apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: tensorflow-horovod-test
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - image: us-central1-docker.pkg.dev/ml-autoscaling/ml-autoscaling-image-registry/horovod:v0.1.12-autoscale-cpu
            name: mpi-launcher
            command:
            - horovodrun
            args:
            - -np
            - "2"
            - --host-discovery-script
            - /etc/mpi/discover_hosts.sh
            - python
            - /autoscale/tensorflow2_keras_mnist_elastic_test.py
            - --autoscale
            - --autoscale-delta-worker
            - "2"
            resources:
              limits:
                cpu: 1
                memory: 2Gi
          serviceAccountName: ml-autoscaling
    Worker:
      replicas: 2
      template:
        spec:
          containers:
          - image: us-central1-docker.pkg.dev/ml-autoscaling/ml-autoscaling-image-registry/horovod:v0.1.12-autoscale-cpu
            name: mpi-worker
            resources:
              limits:
                cpu: 1
                memory: 4Gi
          serviceAccountName: ml-autoscaling
