apiVersion: kubeflow.org/v2autoscale
kind: MPIJob
metadata:
  name: tensorflow-mnist-elastic
spec:
  slotsPerWorker: 3
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - image: localhost:32000/horovod:elastic-base
            name: mpi-launcher
            envFrom:
              - configMapRef:
                  name: proxy-config
            command:
            - horovodrun
            args:
            - -np
            - "2"
            - --min-np
            - "1"
            - --max-np
            - "3"
            - --host-discovery-script
            - /etc/mpi/discover_hosts.sh
            - python
            - /examples/elastic/tensorflow2_synthetic_benchmark_elastic.py
            resources:
              limits:
                cpu: 1
                memory: 2Gi
    Worker:
      replicas: 1
      template:
        spec:
          containers:
          - image: localhost:32000/horovod:elastic-base
            name: mpi-worker
            envFrom:
              - configMapRef:
                  name: proxy-config
            resources:
              limits:
                cpu: 2
                memory: 4Gi
