apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: tensorflow-horovod-test
spec:
  slotsPerWorker: 2
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - image: localhost:32000/horovod:v0.1.1-autoscale-cpu
            name: mpi-launcher
            envFrom:
              - configMapRef:
                  name: proxy-config
            command:
            - horovodrun
            args:
            - -np
            - "2"
            - --host-discovery-script
            - /etc/mpi/discover_hosts.sh
            - python
            - /examples/elastic/tensorflow2_synthetic_benchmark_elastic_custom.py
            - --no-cuda
            resources:
              limits:
                cpu: 2
                memory: 8Gi
    Worker:
      replicas: 2
      template:
        spec:
          containers:
          - image: localhost:32000/horovod:v0.1.1-autoscale-cpu
            name: mpi-worker
            envFrom:
              - configMapRef:
                  name: proxy-config
            resources:
              limits:
                cpu: 2
                memory: 16Gi
