apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: ta-ardi-test-no-autoscaling-1-node
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
            - image: localhost:32000/horovod:v0.1.45-autoscale-cpu
              name: mpi-launcher
              command:
                - horovodrun
              args:
                - -np
                - "1"
                - --host-discovery-script
                - /etc/mpi/discover_hosts.sh
                - python
                - /autoscale/tensorflow2_mnist_elastic_test.py
                - --batch-size
                - "64"
                - --num-epochs
                - "1"
                - --batches-per-epoch
                - "1000"
#                - --autoscale
#                - --autoscale-min-worker
#                - "1"
#                - --autoscale-max-worker
#                - "8"
#                - --autoscale-delta-worker
#                - "1"
#                - --autoscale-efficiency-threshold
#                - "0.01"
#                - --autoscale-throughput-average-batches
#                - "10"
              resources:
                limits:
                  cpu: 1
                  memory: 2Gi
          serviceAccountName: ml-autoscaling
    Worker:
      replicas: 1
      template:
        spec:
          containers:
            - image: localhost:32000/horovod:v0.1.45-autoscale-cpu
              name: mpi-worker
              volumeMounts:
                - name: my-persistent-volume
                  mountPath: /root/.keras/datasets
              resources:
                limits:
                  cpu: 1
                  memory: 2Gi
          volumes:
            - name: my-persistent-volume
              persistentVolumeClaim:
                # specify PVC name you defined
                claimName: mnist-pvc
          serviceAccountName: ml-autoscaling
